### ISSUE TITLE
[Spend-before-Sync] Requested height [over latestheight]  does not exist in the block cache

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#1223] opened 2023-08-31 22:26 UTC
### Describe the issue
When scanning I get this error:

```
CompactBlockProcessor.swift - run() - Line: 535 -> Sync failed with error: rustScanBlocks("Error while scanning blocks: The underlying block store produced the following error: Requested height 2211141 does not exist in the block cache")
```

Latest blockheight reported by synchronizer at the time: 2211137

Please provide a general summary of the issue you're experiencing

#### If so, please list the steps to reproduce below:
1. Run Demo App on mainnet
2. use the test wallet or any other
3. tap "sync blocks"

### Expected behaviour
It should scan without errors

### Actual behaviour + errors
commit: d880d253c54ffa88c5bd7653cff46292fd75df9a

synchronizer shows the error, then resumes.

**Comment by pacu** [comment] 2023-08-31 23:49
Note: Somehow, before switching to the DAGSync feature, I managed to get this error with a different height using `main` but I'm not able to reproduce it again :/

**Comment by LukasKorba** [comment] 2023-09-01 05:42
What is the mainnet server URL in the repo you used? I experienced the same issue but it stared one day and after a few days I was never able to reproduce it. What I've done was to update all dependencies + updated the mainnet URL from electriccoin one to mainnet.lightwalletd.com

**Comment by nuttycom** [comment] 2023-09-01 13:52
One possible source of error: scan ranges are end-exclusive; if a wallet attempts to retrieve and scan the block that corresponds to the end of the chain-tip range, it will fail unless that block has been incidentally mined since the last check of the chain tip.

**Comment by nuttycom** [comment] 2023-09-01 14:35
> What is the mainnet server URL in the repo you used? I experienced the same issue but it started one day and after a few days I was never able to reproduce it. What I've done was to update all dependencies + updated the mainnet URL from electriccoin one to `mainnet.lightwalletd.com`

@pacu ^^^

**Comment by LukasKorba** [comment] 2023-09-01 18:33
I was able to reproduce it and I found the root cause, fix was simple. After I cleanup the code, check tests and probably implement one new for this case, I'll do PR.

**Comment by pacu** [comment] 2023-09-01 23:45
> > What is the mainnet server URL in the repo you used? I experienced the same issue but it started one day and after a few days I was never able to reproduce it. What I've done was to update all dependencies + updated the mainnet URL from electriccoin one to `mainnet.lightwalletd.com`
> 
> @pacu ^^^
I used the demo app as-is

**Comment by LukasKorba** [comment] 2023-09-04 05:21
@pacu can you please try again? Latest feature/DAG-sync

**Comment by pacu** [comment] 2023-09-04 18:46
> @pacu can you please try again? Latest feature/DAG-sync

I did try yesterday and confirmed the fix

https://github.com/zcash/ZcashLightClientKit/pull/1224#issuecomment-1704346712

Do you need me to try again?

**Comment by LukasKorba** [comment] 2023-09-05 09:48
> > @pacu can you please try again? Latest feature/DAG-sync
> 
> I did try yesterday and confirmed the fix
> 
> [#1224 (comment)](https://github.com/zcash/ZcashLightClientKit/pull/1224#issuecomment-1704346712)
> 
> Do you need me to try again?

Thank you for the confirmation, no need to try again. Closing as fixed

**Closed by LukasKorba** 2023-09-05 09:48 UTC
Labels: bug
