### ISSUE TITLE
Support multiple instances of the SDKSynchronizer

### ISSUE THREAD

**Issue by Chlup** [zcash/ZcashLightClientKit#830] opened 2023-03-14 18:29 UTC
Currently if the client app creates multiple instances of the `SDKSynchronizer` horrible things happen. Android support this. They call this feature "Alias". They automatically assign ID (aka alias) to each instance. And then every resource inside the SDK uses alias. So for example path to any database contains this alias. Thanks to this it's safe to create multiple instances of synchronizer on Android and use those independently. We want the same on the iOS.

**Comment by pacu** [comment] 2023-03-21 11:06
this is a duplicate of #209

**Closed by pacu** 2023-03-21 11:06 UTC
